services:
  - type: web
    name: casioproject
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "apache2-foreground"
    ports:
      - port: 80
