services:
  - type: web
    name: casioproject
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile   # <== REMOVE "CasioProject/"
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    ports:
      - port: 10000
