services:
  - type: web
    name: casioproject
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "" # Use CMD from Dockerfile
    ports:
      - port: 8000 # Add this line
