services:
  - type: web
    name: casioproject
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "" # Leave this blank so Dockerfile CMD is used
