services:
  - type: web
    name: casioproject
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
